ALTER TABLE Estado
MODIFY (Nombre_Estado VARCHAR2(20));

BEGIN pkg_estado.InsertarEstado('Activo', 'Disponible'); END;
BEGIN pkg_estado.InsertarEstado('Inactivo', 'No disponible'); END;
BEGIN pkg_estado.InsertarEstado('Pendiente', 'En espera'); END;
BEGIN pkg_estado.InsertarEstado('Proceso', 'En proceso'); END;
BEGIN pkg_estado.InsertarEstado('Cancelado', 'Anulado'); END;
BEGIN pkg_estado.InsertarEstado('Completado', 'Finalizado'); END;
BEGIN pkg_estado.InsertarEstado('Vencido', 'Fuera de tiempo'); END;
BEGIN pkg_estado.InsertarEstado('Programado', 'Con fecha'); END;
BEGIN pkg_estado.InsertarEstado('Retrasado', 'Fuera de plazo'); END;
BEGIN pkg_estado.InsertarEstado('Aceptado', 'Aprobado'); END;
BEGIN pkg_estado.InsertarEstado('Rechazado', 'Denegado'); END;
BEGIN pkg_estado.InsertarEstado('Facturado', 'Con factura'); END;
BEGIN pkg_estado.InsertarEstado('Pagado', 'Con pago'); END;
BEGIN pkg_estado.InsertarEstado('Parcial', 'Pago parcial'); END;
BEGIN pkg_estado.InsertarEstado('Verificado', 'Chequeado'); END;
BEGIN pkg_estado.InsertarEstado('Revisión', 'En revisión'); END;
BEGIN pkg_estado.InsertarEstado('Disponible', 'Listo uso'); END;
BEGIN pkg_estado.InsertarEstado('Agotado', 'Sin stock'); END;
BEGIN pkg_estado.InsertarEstado('Reservado', 'Apartado'); END;
BEGIN pkg_estado.InsertarEstado('Desactivado', 'Fuera de uso'); END;



-- Tabla clientes actualizada
INSERT INTO Clientes VALUES (1, 1, 'María', 'González', 'San José', 'maria.gonzalez@gmail.com');
INSERT INTO Clientes VALUES (2, 1, 'Juan', 'Rodríguez', 'Cartago', 'juan.rodriguez@hotmail.com');
INSERT INTO Clientes VALUES (3, 2, 'Carlos', 'Soto', 'Alajuela', 'carlos.soto@yahoo.com');
INSERT INTO Clientes VALUES (4, 1, 'Ana', 'Jiménez', 'Heredia', 'ana.jimenez@gmail.com');
INSERT INTO Clientes VALUES (5, 3, 'Luis', 'Pérez', 'Puntarenas', 'luis.perez@outlook.com');
INSERT INTO Clientes VALUES (6, 1, 'Laura', 'Ramírez', 'Cartago', 'laura.ramirez@gmail.com');
INSERT INTO Clientes VALUES (7, 4, 'Pedro', 'Campos', 'Guanacaste', 'pedro.campos@gmail.com');
INSERT INTO Clientes VALUES (8, 1, 'Sofía', 'Vargas', 'San José', 'sofia.vargas@gmail.com');
INSERT INTO Clientes VALUES (9, 2, 'Andrés', 'Araya', 'Heredia', 'andres.araya@hotmail.com');
INSERT INTO Clientes VALUES (10, 1, 'Gabriela', 'Rojas', 'Cartago', 'gabriela.rojas@gmail.com');
INSERT INTO Clientes VALUES (11, 5, 'Ricardo', 'Solano', 'San José', 'ricardo.solano@outlook.com');
INSERT INTO Clientes VALUES (12, 1, 'Daniela', 'Acosta', 'Alajuela', 'daniela.acosta@gmail.com');
INSERT INTO Clientes VALUES (13, 3, 'Jorge', 'Cordero', 'Puntarenas', 'jorge.cordero@gmail.com');
INSERT INTO Clientes VALUES (14, 1, 'Natalia', 'Zuñiga', 'Heredia', 'natalia.zuniga@yahoo.com');
INSERT INTO Clientes VALUES (15, 1, 'Esteban', 'Mora', 'San José', 'esteban.mora@gmail.com');
INSERT INTO Clientes VALUES (16, 4, 'Patricia', 'Marín', 'Cartago', 'patricia.marin@gmail.com');
INSERT INTO Clientes VALUES (17, 1, 'Diego', 'Salazar', 'Alajuela', 'diego.salazar@hotmail.com');
INSERT INTO Clientes VALUES (18, 2, 'Josué', 'Leiva', 'Guanacaste', 'josue.leiva@gmail.com');
INSERT INTO Clientes VALUES (19, 1, 'Rebeca', 'Ruiz', 'San José', 'rebeca.ruiz@gmail.com');
INSERT INTO Clientes VALUES (20, 1, 'Kevin', 'Vega', 'Heredia', 'kevin.vega@outlook.com');
INSERT INTO Clientes VALUES (21, 3, 'Isabel', 'Navarro', 'Cartago', 'isabel.navarro@gmail.com');
INSERT INTO Clientes VALUES (22, 1, 'Fernanda', 'Calderón', 'Alajuela', 'fernanda.calderon@yahoo.com');
INSERT INTO Clientes VALUES (23, 5, 'Felipe', 'Ureña', 'San José', 'felipe.urena@gmail.com');
INSERT INTO Clientes VALUES (24, 1, 'Karina', 'Montero', 'Guanacaste', 'karina.montero@gmail.com');
INSERT INTO Clientes VALUES (25, 2, 'Mauricio', 'Vargas', 'Cartago', 'mauricio.vargas@hotmail.com');
INSERT INTO Clientes VALUES (26, 1, 'Valeria', 'Segura', 'Heredia', 'valeria.segura@gmail.com');
INSERT INTO Clientes VALUES (27, 4, 'Paola', 'Hernández', 'San José', 'paola.hernandez@outlook.com');
INSERT INTO Clientes VALUES (28, 1, 'Óscar', 'Carrillo', 'Cartago', 'oscar.carrillo@gmail.com');
INSERT INTO Clientes VALUES (29, 3, 'Jennifer', 'Sandí', 'Alajuela', 'jennifer.sandi@gmail.com');
INSERT INTO Clientes VALUES (30, 1, 'Alex', 'Barquero', 'San José', 'alex.barquero@hotmail.com');
INSERT INTO Clientes VALUES (31, 2, 'Camila', 'Chaves', 'Heredia', 'camila.chaves@gmail.com');
INSERT INTO Clientes VALUES (32, 1, 'Fabián', 'Rojas', 'Alajuela', 'fabian.rojas@gmail.com');
INSERT INTO Clientes VALUES (33, 1, 'Tatiana', 'López', 'Puntarenas', 'tatiana.lopez@hotmail.com');
INSERT INTO Clientes VALUES (34, 3, 'Sebastián', 'Calvo', 'San José', 'sebastian.calvo@gmail.com');
INSERT INTO Clientes VALUES (35, 1, 'Mónica', 'Espinoza', 'Cartago', 'monica.espinoza@gmail.com');
INSERT INTO Clientes VALUES (36, 5, 'Alexander', 'Granados', 'Heredia', 'alexander.granados@gmail.com');
INSERT INTO Clientes VALUES (37, 4, 'Marcela', 'Vargas', 'San José', 'marcela.vargas@hotmail.com');
INSERT INTO Clientes VALUES (38, 1, 'Adriana', 'Alfaro', 'San José', 'adriana.alfaro@gmail.com');
INSERT INTO Clientes VALUES (39, 2, 'Pablo', 'Cubero', 'Alajuela', 'pablo.cubero@hotmail.com');
INSERT INTO Clientes VALUES (40, 1, 'Andrea', 'Céspedes', 'Cartago', 'andrea.cespedes@gmail.com');



--Tabla de inventario actualizada
INSERT INTO Inventario VALUES (1, 1, 'SSD Kingston 240GB', 'Unidad estado sólido nueva', 35000, 12);
INSERT INTO Inventario VALUES (2, 1, 'Memoria RAM 8GB DDR4', 'Kingston HyperX nueva', 28000, 15);
INSERT INTO Inventario VALUES (3, 1, 'Fuente poder 600W', 'EVGA 600W usada funcional', 42000, 4);
INSERT INTO Inventario VALUES (4, 1, 'Placa Madre ASUS H110M', 'ASUS Intel usada', 55000, 3);
INSERT INTO Inventario VALUES (5, 2, 'Cargadores universales laptop', 'Genéricos nuevos', 15000, 10);
INSERT INTO Inventario VALUES (6, 1, 'Disco duro 1TB', 'Seagate SATA nuevo', 42000, 8);
INSERT INTO Inventario VALUES (7, 3, 'Kit tornillos PC', 'Bolsitas de 50pzas nuevos', 2000, 25);
INSERT INTO Inventario VALUES (8, 1, 'Tarjeta video GT 1030', 'NVIDIA usada', 60000, 2);
INSERT INTO Inventario VALUES (9, 1, 'Cable HDMI 1.5m', 'Genérico nuevo', 3500, 20);
INSERT INTO Inventario VALUES (10, 4, 'Spray aire comprimido', 'Limpieza interna nuevo', 3000, 18);
INSERT INTO Inventario VALUES (11, 1, 'Pasta térmica Arctic', '1g nueva original', 4500, 30);
INSERT INTO Inventario VALUES (12, 1, 'Memoria RAM 4GB DDR3', 'Kingston usada', 12000, 7);
INSERT INTO Inventario VALUES (13, 2, 'Mouse Logitech M90', 'Nuevo retail', 7000, 11);
INSERT INTO Inventario VALUES (14, 1, 'Teclado genérico USB', 'Nuevo económico', 6000, 9);
INSERT INTO Inventario VALUES (15, 1, 'Pantalla LCD 15.6"', 'Repuesto laptop usado', 55000, 3);
INSERT INTO Inventario VALUES (16, 1, 'Batería HP 14"', 'Repuesto usada', 30000, 5);
INSERT INTO Inventario VALUES (17, 3, 'Alcohol isopropílico', 'Botella 99% nuevo', 2500, 14);
INSERT INTO Inventario VALUES (18, 1, 'SSD NVMe 500GB', 'WesternDigital Blue nuevo', 89000, 6);
INSERT INTO Inventario VALUES (19, 1, 'Tarjeta WiFi USB', 'TP-Link nuevo', 9500, 12);
INSERT INTO Inventario VALUES (20, 5, 'Cables SATA III', 'Nuevos empacados', 1800, 22);
INSERT INTO Inventario VALUES (21, 1, 'Disipador Cooler Master', 'Con ventilador usado', 27000, 5);
INSERT INTO Inventario VALUES (22, 2, 'Memoria RAM 16GB DDR4', 'Crucial Ballistix nueva', 58000, 4);
INSERT INTO Inventario VALUES (23, 1, 'SSD 120GB Genérico', 'Nuevo en caja', 25000, 9);
INSERT INTO Inventario VALUES (24, 1, 'Hub USB 4 puertos', 'TP-Link nuevo', 8000, 15);
INSERT INTO Inventario VALUES (25, 1, 'Antena WiFi interna', 'Repuesto laptop usado', 3500, 6);
INSERT INTO Inventario VALUES (26, 3, 'Pantalla LED 17"', 'Para PC, usada', 45000, 3);
INSERT INTO Inventario VALUES (27, 4, 'Caja herramienta básica', 'Reparación portátil', 20000, 7);
INSERT INTO Inventario VALUES (28, 1, 'Cargador Lenovo 20V', 'Nuevo original', 23000, 5);
INSERT INTO Inventario VALUES (29, 1, 'Tarjeta madre MSI B450', 'AMD Ryzen soporte nueva', 98000, 2);
INSERT INTO Inventario VALUES (30, 1, 'Ventilador gabinete 120mm', 'Cooler Master nuevo', 5500, 20);
INSERT INTO Inventario VALUES (31, 2, 'Memoria RAM 2GB DDR2', 'Usada funcionando', 5000, 8);
INSERT INTO Inventario VALUES (32, 1, 'Pasta térmica genérica', 'Nuevas en sobre', 1800, 25);
INSERT INTO Inventario VALUES (33, 1, 'Fuente genérica 450W', 'Usada prueba', 21000, 4);
INSERT INTO Inventario VALUES (34, 1, 'Módulo WiFi M.2', 'Laptop nuevo', 12000, 3);
INSERT INTO Inventario VALUES (35, 1, 'Cable VGA 1.5m', 'Genérico nuevo', 2800, 12);
INSERT INTO Inventario VALUES (36, 3, 'Caja ATX semitorre', 'Case usado en buen estado', 39000, 2);
INSERT INTO Inventario VALUES (37, 1, 'Cámara web USB', 'Logitech nueva', 27000, 6);
INSERT INTO Inventario VALUES (38, 1, 'Multímetro digital', 'Genérico nuevo', 16000, 4);
INSERT INTO Inventario VALUES (39, 1, 'Soplador eléctrico', 'Limpieza de hardware', 46000, 2);
INSERT INTO Inventario VALUES (40, 5, 'CD Windows 10 Pro OEM', 'Licencia incluida nueva', 60000, 3);
INSERT INTO Inventario VALUES (41, 1, 'Tarjeta de video GTX 1050 Ti', 'NVIDIA usada funcionando', 135000, 2);
INSERT INTO Inventario VALUES (42, 1, 'Router TP-Link Archer C20', 'Nuevo empacado', 29000, 6);
INSERT INTO Inventario VALUES (43, 3, 'Kit destornilladores de precisión', 'Para reparación, nuevo', 8500, 10);
INSERT INTO Inventario VALUES (44, 1, 'Disco duro 500GB', 'Western Digital usado', 18000, 7);
INSERT INTO Inventario VALUES (45, 2, 'Placa madre Dell OEM', 'Repuesto usado', 25000, 3);
INSERT INTO Inventario VALUES (46, 1, 'Tarjeta sonido PCIe', 'Creative nueva', 17000, 5);
INSERT INTO Inventario VALUES (47, 1, 'Hub USB tipo C', 'Nuevo de 6 puertos', 12000, 8);
INSERT INTO Inventario VALUES (48, 5, 'Fuente certificada Corsair 650W', 'Nueva 80+ Bronze', 89000, 1);
INSERT INTO Inventario VALUES (49, 1, 'Memoria RAM 32GB DDR4', 'Corsair Vengeance nueva', 145000, 2);
INSERT INTO Inventario VALUES (50, 1, 'Adaptador USB – Ethernet', 'Nuevo genérico', 6000, 15);
INSERT INTO Inventario VALUES (51, 3, 'Batería Dell Inspiron', 'Usada funcional', 28000, 4);
INSERT INTO Inventario VALUES (52, 1, 'Switch 8 puertos', 'TP-Link nuevo', 22000, 6);
INSERT INTO Inventario VALUES (53, 1, 'Teclado mecánico Redragon', 'Nuevo iluminación RGB', 35000, 5);
INSERT INTO Inventario VALUES (54, 2, 'Mouse gamer Razer', 'Usado buen estado', 25000, 3);
INSERT INTO Inventario VALUES (55, 1, 'Placa WiFi PCIe', 'ASUS nueva', 19000, 7);
INSERT INTO Inventario VALUES (56, 1, 'Kit limpieza premium', 'Brochas y líquidos nuevo', 7000, 13);
INSERT INTO Inventario VALUES (57, 1, 'M.2 NVMe 250GB', 'Samsung 970 usado', 42000, 4);
INSERT INTO Inventario VALUES (58, 4, 'Cinta envolvente cables', 'Organizadora nueva', 2000, 30);
INSERT INTO Inventario VALUES (59, 1, 'Parlantes Logitech Z120', 'Nuevo 2.0 USB', 16000, 9);
INSERT INTO Inventario VALUES (60, 5, 'Kit reparación soldadura', 'Herramientas intermedias', 31000, 3);
INSERT INTO Inventario VALUES (61, 1, 'Cable DisplayPort 2m', 'Genérico nuevo', 5500, 12);
INSERT INTO Inventario VALUES (62, 1, 'SSD 1TB Crucial', 'Nuevo en caja', 185000, 3);
INSERT INTO Inventario VALUES (63, 3, 'Monitor 24" LG', 'Usado sin caja', 85000, 2);
INSERT INTO Inventario VALUES (64, 1, 'Soporte pasta térmica', 'Jeringa Arctic nueva', 6000, 20);
INSERT INTO Inventario VALUES (65, 1, 'Motherboard ASUS Prime B460', 'Nueva Intel 10th gen', 110000, 2);
INSERT INTO Inventario VALUES (66, 2, 'Memoria RAM 8GB DDR3', 'Usada Crucial', 15000, 6);
INSERT INTO Inventario VALUES (67, 1, 'SSD Kingston 480GB', 'Nuevo', 65000, 4);
INSERT INTO Inventario VALUES (68, 4, 'Cableado modular PSU', 'Repuestos Corsair', 9000, 10);
INSERT INTO Inventario VALUES (69, 1, 'Tarjeta gráfica RX 570', 'Usada Gigabyte', 125000, 2);
INSERT INTO Inventario VALUES (70, 1, 'Ventilador portátil USB', 'Mini nuevo', 2500, 25);
INSERT INTO Inventario VALUES (71, 3, 'Tarjeta WiFi Mini PCIe', 'Repuesto laptop usado', 9500, 6);
INSERT INTO Inventario VALUES (72, 1, 'Guantes antiestáticos', 'Nuevo par', 3000, 14);
INSERT INTO Inventario VALUES (73, 1, 'Cable USB tipo C 1m', 'Reforzado nuevo', 4000, 25);
INSERT INTO Inventario VALUES (74, 1, 'Spray limpiador contactos', 'Nuevo aerosol', 3800, 15);
INSERT INTO Inventario VALUES (75, 2, 'Placa madre HP OEM', 'Usada funcional', 20000, 3);
INSERT INTO Inventario VALUES (76, 1, 'Webcam 1080p genérica', 'Nueva', 17500, 6);
INSERT INTO Inventario VALUES (77, 1, 'Kit bandas sujetacables', '50 unidades', 1500, 30);
INSERT INTO Inventario VALUES (78, 5, 'SSD NVMe 2TB Samsung', 'Nuevo 980 PRO', 250000, 1);
INSERT INTO Inventario VALUES (79, 1, 'Unidad DVD externa USB', 'ASUS nueva', 27000, 4);
INSERT INTO Inventario VALUES (80, 1, 'Tarjeta FireWire PCIe', 'Repuesto usada', 12000, 2);
INSERT INTO Inventario VALUES (81, 1, 'Extensor WiFi TP-Link', 'Nuevo empacado', 23000, 5);
INSERT INTO Inventario VALUES (82, 2, 'Memoria RAM 1GB DDR2', 'Usada Kingston', 3500, 7);
INSERT INTO Inventario VALUES (83, 1, 'Tarjeta captura video USB', 'Genérico nuevo', 18000, 6);
INSERT INTO Inventario VALUES (84, 1, 'Controlador Fan RGB', 'Cooler Master nuevo', 9000, 8);
INSERT INTO Inventario VALUES (85, 3, 'Pantalla LCD 14"', 'Repuesto laptop usada', 42000, 3);
INSERT INTO Inventario VALUES (86, 1, 'Fuente Thermaltake 750W', 'Nueva 80+ Gold', 120000, 2);
INSERT INTO Inventario VALUES (87, 1, 'Soporte monitor articulado', 'Genérico nuevo', 33000, 4);
INSERT INTO Inventario VALUES (88, 5, 'Mouse pad grande RGB', 'Gamer nuevo', 10500, 10);
INSERT INTO Inventario VALUES (89, 1, 'Tarjeta red gigabit PCIe', 'TP-Link nueva', 15000, 7);
INSERT INTO Inventario VALUES (90, 1, 'Memoria Optane Intel 32GB', 'Nueva acelerador', 65000, 3);
INSERT INTO Inventario VALUES (91, 4, 'Pantalla Touch 13.3"', 'Usada ultrabook', 62000, 2);
INSERT INTO Inventario VALUES (92, 1, 'Kit extractor teclas', 'Mecánicos nuevo', 2500, 20);
INSERT INTO Inventario VALUES (93, 1, 'Switch KVM 2 Puertos', 'Controlar 2 PCs nuevo', 27500, 3);
INSERT INTO Inventario VALUES (94, 2, 'Tarjeta GT 710', 'NVIDIA usada', 23000, 4);
INSERT INTO Inventario VALUES (95, 1, 'Hub USB 7 puertos', 'Genérico nuevo', 9500, 9);
INSERT INTO Inventario VALUES (96, 1, 'SSD Patriot 256GB', 'Nuevo en caja', 38000, 5);
INSERT INTO Inventario VALUES (97, 2, 'Regrabador DVD SATA', 'Usado funcional', 9500, 6);
INSERT INTO Inventario VALUES (98, 1, 'Adaptador PS/2 a USB', 'Nuevo', 1800, 15);
INSERT INTO Inventario VALUES (99, 3, 'Microprocesador i5-3470', 'Usado Intel', 48000, 3);
INSERT INTO Inventario VALUES (100, 1, 'Tarjeta RAID PCIe', 'Nuevas 4 puertos SATA', 68000, 2);



--Tabla de Gestion_Servicios actualizada
INSERT INTO Gestion_Servicios VALUES (1, 1, 1, 'Instalación SSD Kingston 240GB', 'Instalación profesional de unidad SSD Kingston 240GB nueva');
INSERT INTO Gestion_Servicios VALUES (2, 1, 2, 'Ampliación de Memoria RAM 8GB DDR4', 'Agregar módulo de memoria RAM Kingston HyperX 8GB DDR4');
INSERT INTO Gestion_Servicios VALUES (3, 1, 3, 'Reemplazo Fuente de Poder 600W', 'Sustitución de fuente de poder EVGA 600W usada funcional');
INSERT INTO Gestion_Servicios VALUES (4, 1, 4, 'Reparación Placa Madre ASUS H110M', 'Reparación o reemplazo de placa madre ASUS Intel usada');
INSERT INTO Gestion_Servicios VALUES (5, 2, 5, 'Suministro y Cambio de Cargadores Universales', 'Reemplazo de cargadores universales nuevos genéricos');
INSERT INTO Gestion_Servicios VALUES (6, 1, 6, 'Reemplazo Disco Duro 1TB Seagate', 'Sustitución de disco duro Seagate SATA nuevo');
INSERT INTO Gestion_Servicios VALUES (7, 3, 7, 'Suministro de Kit de Tornillos PC', 'Provisión de bolsitas de tornillos para PC (50 piezas nuevas)');
INSERT INTO Gestion_Servicios VALUES (8, 1, 8, 'Instalación Tarjeta Video GT 1030', 'Colocación de tarjeta gráfica NVIDIA usada');
INSERT INTO Gestion_Servicios VALUES (9, 1, 9, 'Cambio Cable HDMI 1.5m', 'Reemplazo de cable HDMI genérico nuevo');
INSERT INTO Gestion_Servicios VALUES (10, 4, 10, 'Limpieza interna con spray aire comprimido', 'Limpieza profunda de hardware con spray de aire comprimido');
INSERT INTO Gestion_Servicios VALUES (11, 1, 11, 'Aplicación Pasta Térmica Arctic', 'Colocación de pasta térmica Arctic original 1g');
INSERT INTO Gestion_Servicios VALUES (12, 1, 12, 'Actualización Memoria RAM 4GB DDR3', 'Sustitución de módulo RAM Kingston usada');
INSERT INTO Gestion_Servicios VALUES (13, 2, 13, 'Configuración Mouse Logitech M90', 'Instalación y configuración de mouse Logitech nuevo');
INSERT INTO Gestion_Servicios VALUES (14, 1, 14, 'Instalación Teclado Genérico USB', 'Colocación de teclado USB nuevo económico');
INSERT INTO Gestion_Servicios VALUES (15, 1, 15, 'Reparación Pantalla LCD 15.6"', 'Cambio de pantalla de laptop usada');
INSERT INTO Gestion_Servicios VALUES (16, 1, 16, 'Reemplazo Batería HP 14"', 'Sustitución de batería usada para laptop HP');
INSERT INTO Gestion_Servicios VALUES (17, 3, 17, 'Limpieza con Alcohol Isopropílico', 'Limpieza y desinfección interna con alcohol isopropílico 99%');
INSERT INTO Gestion_Servicios VALUES (18, 1, 18, 'Instalación SSD NVMe 500GB WD Blue', 'Instalación de SSD NVMe Western Digital Blue nuevo');
INSERT INTO Gestion_Servicios VALUES (19, 1, 19, 'Instalación Tarjeta WiFi USB TP-Link', 'Configuración y colocación de tarjeta WiFi USB TP-Link nueva');
INSERT INTO Gestion_Servicios VALUES (20, 5, 20, 'Cambio Cables SATA III', 'Sustitución de cables SATA nuevos empacados');


--Tabla de Empleados actualizada 
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (1, 1, 'Juan', 'Pérez', 'juan.perez@empresa.com', 'Gerente de Proyectos', '65000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (2, 1, 'Ana', 'García', 'ana.garcia@empresa.com', 'Analista de Datos', '58000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (3, 1, 'Carlos', 'López', 'carlos.lopez@empresa.com', 'Desarrollador Senior', '85000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (4, 1, 'Sofía', 'Martínez', 'sofia.martinez@empresa.com', 'Diseñadora UX/UI', '72000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (5, 2, 'Pedro', 'Sánchez', 'pedro.sanchez@empresa.com', 'Especialista en Marketing', '60000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (6, 1, 'Laura', 'Ramírez', 'laura.ramirez@empresa.com', 'Contadora', '55000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (7, 1, 'José', 'Torres', 'jose.torres@empresa.com', 'Director de Ventas', '95000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (8, 1, 'María', 'Díaz', 'maria.diaz@empresa.com', 'Asistente Administrativa', '45000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (9, 3, 'Felipe', 'Vargas', 'felipe.vargas@empresa.com', 'Ingeniero de Software', '78000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (10, 1, 'Gabriela', 'Castro', 'gabriela.castro@empresa.com', 'Recursos Humanos', '62000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (11, 1, 'Diego', 'Rojas', 'diego.rojas@empresa.com', 'Técnico de Soporte', '48000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (12, 1, 'Patricia', 'Herrera', 'patricia.herrera@empresa.com', 'Especialista en QA', '68000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (13, 1, 'Ricardo', 'Gómez', 'ricardo.gomez@empresa.com', 'Arquitecto de Soluciones', '110000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (14, 2, 'Andrea', 'Núñez', 'andrea.nunez@empresa.com', 'Coordinadora de Eventos', '57000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (15, 1, 'Manuel', 'Salazar', 'manuel.salazar@empresa.com', 'Gestor de Contenido', '59000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (16, 1, 'Cristina', 'Ortega', 'cristina.ortega@empresa.com', 'Analista Financiera', '75000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (17, 3, 'Fernando', 'Guerrero', 'fernando.guerrero@empresa.com', 'Consultor Senior', '92000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (18, 1, 'Isabel', 'Morales', 'isabel.morales@empresa.com', 'Asistente de Marketing', '51000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (19, 1, 'Daniel', 'Silva', 'daniel.silva@empresa.com', 'Jefe de Equipo', '88000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (20, 1, 'Valeria', 'Ríos', 'valeria.rios@empresa.com', 'Especialista en SEO', '64000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (21, 1, 'Andrés', 'Soto', 'andres.soto@empresa.com', 'Desarrollador Junior', '42000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (22, 1, 'Elena', 'Mendoza', 'elena.mendoza@empresa.com', 'Directora de Contabilidad', '98000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (23, 1, 'Sergio', 'Castañeda', 'sergio.castaneda@empresa.com', 'Analista de Negocios', '70000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (24, 1, 'Paola', 'Velasco', 'paola.velasco@empresa.com', 'Coordinadora de RH', '59000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (25, 2, 'Javier', 'Luna', 'javier.luna@empresa.com', 'Representante de Ventas', '50000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (26, 1, 'Mónica', 'Fuentes', 'monica.fuentes@empresa.com', 'Gerente de Operaciones', '88000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (27, 1, 'Roberto', 'Paz', 'roberto.paz@empresa.com', 'Especialista en IT', '65000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (28, 1, 'Diana', 'Miranda', 'diana.miranda@empresa.com', 'Auditora', '77000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (29, 3, 'Pablo', 'Mora', 'pablo.mora@empresa.com', 'Programador', '60000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (30, 1, 'Verónica', 'Silva', 'veronica.silva@empresa.com', 'Investigadora de Mercado', '68000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (31, 1, 'Antonio', 'Paredes', 'antonio.paredes@empresa.com', 'Coordinador de Logística', '63000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (32, 1, 'Lucía', 'Guzmán', 'lucia.guzman@empresa.com', 'Especialista en Marketing Digital', '71000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (33, 1, 'Martín', 'Acosta', 'martin.acosta@empresa.com', 'Director de Marketing', '105000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (34, 2, 'Natalia', 'Fuentes', 'natalia.fuentes@empresa.com', 'Diseñadora Gráfica', '56000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (35, 1, 'Alejandro', 'Reyes', 'alejandro.reyes@empresa.com', 'Jefe de Producción', '80000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (36, 1, 'Cecilia', 'Peralta', 'cecilia.peralta@empresa.com', 'Asistente de Contabilidad', '47000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (37, 3, 'Gustavo', 'Castro', 'gustavo.castro@empresa.com', 'Estratega de Contenido', '70000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (38, 1, 'Emilia', 'Méndez', 'emilia.mendez@empresa.com', 'Ejecutiva de Cuentas', '62000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (39, 1, 'Jorge', 'Sáenz', 'jorge.saenz@empresa.com', 'Gerente de TI', '95000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (40, 1, 'Marcela', 'Vidal', 'marcela.vidal@empresa.com', 'Asistente de Recursos Humanos', '53000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (41, 1, 'Luis', 'Cabrera', 'luis.cabrera@empresa.com', 'Ingeniero Civil', '75000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (42, 1, 'Isabella', 'Rojas', 'isabella.rojas@empresa.com', 'Jefa de Calidad', '81000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (43, 1, 'Ignacio', 'Herrera', 'ignacio.herrera@empresa.com', 'Consultor Financiero', '90000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (44, 1, 'Paula', 'Molina', 'paula.molina@empresa.com', 'Especialista en Comunicación', '66000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (45, 2, 'Vicente', 'Méndez', 'vicente.mendez@empresa.com', 'Director de Operaciones', '120000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (46, 1, 'Adriana', 'Cortés', 'adriana.cortes@empresa.com', 'Diseñadora de Producto', '78000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (47, 1, 'Mario', 'Navarro', 'mario.navarro@empresa.com', 'Desarrollador Full Stack', '85000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (48, 1, 'Silvia', 'Ramírez', 'silvia.ramirez@empresa.com', 'Jefa de Departamento', '98000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (49, 3, 'Fabián', 'Vargas', 'fabian.vargas@empresa.com', 'Analista de Seguridad', '75000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (50, 1, 'Camila', 'Morales', 'camila.morales@empresa.com', 'Especialista en Adquisiciones', '69000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (51, 1, 'Álvaro', 'Guerrero', 'alvaro.guerrero@empresa.com', 'Técnico de Redes', '52000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (52, 1, 'Carolina', 'Ortega', 'carolina.ortega@empresa.com', 'Gerente de Contenido', '83000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (53, 1, 'Héctor', 'Ruiz', 'hector.ruiz@empresa.com', 'Estratega de Negocios', '115000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (54, 2, 'Clara', 'Reyes', 'clara.reyes@empresa.com', 'Asistente Legal', '60000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (55, 1, 'Óscar', 'Peralta', 'oscar.peralta@empresa.com', 'Supervisor de Almacén', '55000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (56, 1, 'Julia', 'Silva', 'julia.silva@empresa.com', 'Técnica de Laboratorio', '49000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (57, 3, 'Rubén', 'Vidal', 'ruben.vidal@empresa.com', 'Especialista en Ciberseguridad', '95000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (58, 1, 'Alejandra', 'Sáenz', 'alejandra.saenz@empresa.com', 'Gerente de Producto', '105000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (59, 1, 'Fidel', 'Velasco', 'fidel.velasco@empresa.com', 'Diseñador Web', '68000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (60, 1, 'Marisol', 'Luna', 'marisol.luna@empresa.com', 'Coordinadora de Proyectos', '74000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (61, 1, 'Guillermo', 'Díaz', 'guillermo.diaz@empresa.com', 'Contador Senior', '80000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (62, 1, 'Leticia', 'Castro', 'leticia.castro@empresa.com', 'Jefa de Equipo de Ventas', '85000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (63, 1, 'Raúl', 'Silva', 'raul.silva@empresa.com', 'Asistente de Gerencia', '55000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (64, 1, 'Susana', 'Ríos', 'susana.rios@empresa.com', 'Especialista en Logística', '65000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (65, 2, 'Enrique', 'Pérez', 'enrique.perez@empresa.com', 'Desarrollador de Apps', '75000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (66, 1, 'Sara', 'Martínez', 'sara.martinez@empresa.com', 'Analista de Calidad', '61000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (67, 1, 'Eduardo', 'Sánchez', 'eduardo.sanchez@empresa.com', 'Gerente de Sucursal', '90000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (68, 1, 'Renata', 'Fuentes', 'renata.fuentes@empresa.com', 'Técnica de Mantenimiento', '50000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (69, 3, 'Tomás', 'López', 'tomas.lopez@empresa.com', 'Ingeniero de Sistemas', '82000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (70, 1, 'Valeria', 'Morales', 'valeria.morales@empresa.com', 'Asesora Financiera', '72000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (71, 1, 'Ricardo', 'Gómez', 'ricardo.gomez@empresa.com', 'Coordinador de Marketing', '69000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (72, 1, 'Paula', 'Núñez', 'paula.nunez@empresa.com', 'Jefa de Sección', '78000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (73, 1, 'Alejandro', 'Díaz', 'alejandro.diaz@empresa.com', 'Especialista en RRHH', '64000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (74, 2, 'Fernanda', 'Soto', 'fernanda.soto@empresa.com', 'Asistente de Cuentas', '53000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (75, 1, 'Héctor', 'Torres', 'hector.torres@empresa.com', 'Jefe de Departamento', '95000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (76, 1, 'Viviana', 'García', 'viviana.garcia@empresa.com', 'Analista de Sistemas', '76000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (77, 1, 'Gustavo', 'Ramírez', 'gustavo.ramirez@empresa.com', 'Especialista en Soporte', '58000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (78, 1, 'Lorena', 'Herrera', 'lorena.herrera@empresa.com', 'Coordinadora de Operaciones', '71000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (79, 3, 'Esteban', 'Peralta', 'esteban.peralta@empresa.com', 'Desarrollador Junior', '45000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (80, 1, 'Marisol', 'Vargas', 'marisol.vargas@empresa.com', 'Asistente Administrativa', '48000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (81, 1, 'Andrés', 'Silva', 'andres.silva@empresa.com', 'Gerente de TI', '110000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (82, 1, 'Valeria', 'Castro', 'valeria.castro@empresa.com', 'Especialista en Marketing', '70000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (83, 1, 'Arturo', 'Mora', 'arturo.mora@empresa.com', 'Analista de Datos', '62000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (84, 1, 'Gabriela', 'López', 'gabriela.lopez@empresa.com', 'Contadora Senior', '85000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (85, 2, 'Javier', 'Salazar', 'javier.salazar@empresa.com', 'Diseñador Gráfico', '58000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (86, 1, 'Sofía', 'Paredes', 'sofia.paredes@empresa.com', 'Especialista en Contenido', '66000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (87, 1, 'Manuel', 'Ortiz', 'manuel.ortiz@empresa.com', 'Gerente de Proyectos', '95000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (88, 1, 'Laura', 'Reyes', 'laura.reyes@empresa.com', 'Asistente de Marketing', '51000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (89, 3, 'Juan', 'Vargas', 'juan.vargas@empresa.com', 'Desarrollador Full Stack', '88000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (90, 1, 'María', 'Fuentes', 'maria.fuentes@empresa.com', 'Especialista en SEO', '64000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (91, 1, 'José', 'Pérez', 'jose.perez@empresa.com', 'Técnico de Soporte', '48000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (92, 1, 'Ana', 'García', 'ana.garcia@empresa.com', 'Especialista en QA', '68000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (93, 1, 'Carlos', 'Martínez', 'carlos.martinez@empresa.com', 'Arquitecto de Soluciones', '110000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (94, 2, 'Luisa', 'Díaz', 'luisa.diaz@empresa.com', 'Coordinadora de Eventos', '57000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (95, 1, 'Felipe', 'Sánchez', 'felipe.sanchez@empresa.com', 'Gestor de Contenido', '59000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (96, 1, 'Cristina', 'Ramírez', 'cristina.ramirez@empresa.com', 'Analista Financiera', '75000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (97, 1, 'Fernando', 'López', 'fernando.lopez@empresa.com', 'Consultor Senior', '92000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (98, 1, 'Isabel', 'Gómez', 'isabel.gomez@empresa.com', 'Asistente de Marketing', '51000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (99, 3, 'Daniel', 'Núñez', 'daniel.nunez@empresa.com', 'Jefe de Equipo', '88000');
INSERT INTO Empleados (Empleado_ID, Estado_ID, Nombre_Empleado, Apellido_Empleado, Email_Empleado, Puesto, Salario) VALUES (100, 1, 'Valeria', 'Vargas', 'valeria.vargas@empresa.com', 'Especialista en SEO', '64000');



-- Tabla de Cotizaciones actualizada
INSERT INTO Cotizaciones VALUES (1,3,5,2,14,DATE '2025-01-14');
INSERT INTO Cotizaciones VALUES (2,4,26,8,27,DATE '2025-02-19');
INSERT INTO Cotizaciones VALUES (3,5,13,7,45,DATE '2025-02-05');
INSERT INTO Cotizaciones VALUES (4,6,72,4,8,DATE '2025-02-28');
INSERT INTO Cotizaciones VALUES (5,8,54,13,33,DATE '2025-03-11');
INSERT INTO Cotizaciones VALUES (6,4,39,18,61,DATE '2025-03-25');
INSERT INTO Cotizaciones VALUES (7,3,67,5,19,DATE '2025-04-02');
INSERT INTO Cotizaciones VALUES (8,5,2,6,56,DATE '2025-04-09');
INSERT INTO Cotizaciones VALUES (9,8,11,3,41,DATE '2025-04-15');
INSERT INTO Cotizaciones VALUES (10,6,93,11,72,DATE '2025-04-29');

INSERT INTO Cotizaciones VALUES (11,5,15,9,6,DATE '2025-05-06');
INSERT INTO Cotizaciones VALUES (12,3,48,14,88,DATE '2025-05-19');
INSERT INTO Cotizaciones VALUES (13,4,9,19,7,DATE '2025-05-25');
INSERT INTO Cotizaciones VALUES (14,8,32,20,24,DATE '2025-06-02');
INSERT INTO Cotizaciones VALUES (15,6,77,8,3,DATE '2025-06-10');
INSERT INTO Cotizaciones VALUES (16,3,60,16,55,DATE '2025-06-21');
INSERT INTO Cotizaciones VALUES (17,4,80,4,2,DATE '2025-06-30');
INSERT INTO Cotizaciones VALUES (18,5,3,18,70,DATE '2025-07-14');
INSERT INTO Cotizaciones VALUES (19,6,28,1,14,DATE '2025-07-25');
INSERT INTO Cotizaciones VALUES (20,8,90,12,99,DATE '2025-07-31');

INSERT INTO Cotizaciones VALUES (21,8,73,4,65,DATE '2025-08-03');
INSERT INTO Cotizaciones VALUES (22,3,36,10,11,DATE '2025-08-09');
INSERT INTO Cotizaciones VALUES (23,4,25,9,19,DATE '2025-08-17');
INSERT INTO Cotizaciones VALUES (24,3,57,2,5,DATE '2025-08-24');
INSERT INTO Cotizaciones VALUES (25,5,41,11,17,DATE '2025-08-31');
INSERT INTO Cotizaciones VALUES (26,6,38,3,25,DATE '2025-09-06');
INSERT INTO Cotizaciones VALUES (27,4,88,15,33,DATE '2025-09-15');
INSERT INTO Cotizaciones VALUES (28,5,14,6,44,DATE '2025-09-23');
INSERT INTO Cotizaciones VALUES (29,3,63,18,76,DATE '2025-09-30');
INSERT INTO Cotizaciones VALUES (30,8,79,7,28,DATE '2025-10-06');

INSERT INTO Cotizaciones VALUES (31,3,19,1,37,DATE '2025-10-11');
INSERT INTO Cotizaciones VALUES (32,5,94,13,50,DATE '2025-10-18');
INSERT INTO Cotizaciones VALUES (33,4,44,5,22,DATE '2025-10-29');
INSERT INTO Cotizaciones VALUES (34,6,12,20,56,DATE '2025-11-02');
INSERT INTO Cotizaciones VALUES (35,5,29,7,2,DATE '2025-11-05');
INSERT INTO Cotizaciones VALUES (36,3,99,4,83,DATE '2025-11-09');
INSERT INTO Cotizaciones VALUES (37,8,49,10,14,DATE '2025-11-14');
INSERT INTO Cotizaciones VALUES (38,4,75,18,17,DATE '2025-11-18');
INSERT INTO Cotizaciones VALUES (39,6,24,9,33,DATE '2025-11-23');
INSERT INTO Cotizaciones VALUES (40,5,8,6,60,DATE '2025-11-30');

INSERT INTO Cotizaciones VALUES (41,3,33,5,11,DATE '2025-12-06');
INSERT INTO Cotizaciones VALUES (42,4,69,19,44,DATE '2025-12-14');
INSERT INTO Cotizaciones VALUES (43,6,52,2,21,DATE '2025-12-18');
INSERT INTO Cotizaciones VALUES (44,5,22,15,95,DATE '2025-12-22');
INSERT INTO Cotizaciones VALUES (45,8,96,13,77,DATE '2025-12-28');
INSERT INTO Cotizaciones VALUES (46,3,35,5,12,DATE '2025-01-08');
INSERT INTO Cotizaciones VALUES (47,6,7,1,81,DATE '2025-01-18');
INSERT INTO Cotizaciones VALUES (48,5,61,12,5,DATE '2025-01-27');
INSERT INTO Cotizaciones VALUES (49,4,70,14,26,DATE '2025-02-07');
INSERT INTO Cotizaciones VALUES (50,8,16,19,32,DATE '2025-02-14');

INSERT INTO Cotizaciones VALUES (51,6,84,18,65,DATE '2025-02-28');
INSERT INTO Cotizaciones VALUES (52,5,47,4,99,DATE '2025-03-05');
INSERT INTO Cotizaciones VALUES (53,3,85,9,36,DATE '2025-03-11');
INSERT INTO Cotizaciones VALUES (54,4,58,6,42,DATE '2025-03-15');
INSERT INTO Cotizaciones VALUES (55,8,82,1,48,DATE '2025-03-21');
INSERT INTO Cotizaciones VALUES (56,6,43,11,79,DATE '2025-03-29');
INSERT INTO Cotizaciones VALUES (57,5,91,16,6,DATE '2025-04-05');
INSERT INTO Cotizaciones VALUES (58,4,52,4,51,DATE '2025-04-12');
INSERT INTO Cotizaciones VALUES (59,6,37,2,13,DATE '2025-04-19');
INSERT INTO Cotizaciones VALUES (60,3,30,13,59,DATE '2025-04-27');

INSERT INTO Cotizaciones VALUES (61,5,2,7,88,DATE '2025-05-03');
INSERT INTO Cotizaciones VALUES (62,8,11,14,18,DATE '2025-05-11');
INSERT INTO Cotizaciones VALUES (63,4,99,6,45,DATE '2025-05-17');
INSERT INTO Cotizaciones VALUES (64,3,56,20,11,DATE '2025-05-28');
INSERT INTO Cotizaciones VALUES (65,6,18,9,67,DATE '2025-06-03');
INSERT INTO Cotizaciones VALUES (66,5,31,1,29,DATE '2025-06-11');
INSERT INTO Cotizaciones VALUES (67,3,41,8,77,DATE '2025-06-20');
INSERT INTO Cotizaciones VALUES (68,4,92,12,90,DATE '2025-06-28');
INSERT INTO Cotizaciones VALUES (69,6,25,7,7,DATE '2025-07-11');
INSERT INTO Cotizaciones VALUES (70,8,13,5,56,DATE '2025-07-20');

INSERT INTO Cotizaciones VALUES (71,3,73,12,33,DATE '2025-07-29');
INSERT INTO Cotizaciones VALUES (72,4,45,16,75,DATE '2025-08-06');
INSERT INTO Cotizaciones VALUES (73,8,32,14,9,DATE '2025-08-16');
INSERT INTO Cotizaciones VALUES (74,5,87,6,43,DATE '2025-08-22');
INSERT INTO Cotizaciones VALUES (75,3,64,19,4,DATE '2025-09-01');
INSERT INTO Cotizaciones VALUES (76,6,21,10,68,DATE '2025-09-09');
INSERT INTO Cotizaciones VALUES (77,5,76,2,12,DATE '2025-09-19');
INSERT INTO Cotizaciones VALUES (78,4,14,4,100,DATE '2025-09-28');
INSERT INTO Cotizaciones VALUES (79,8,94,3,63,DATE '2025-10-05');
INSERT INTO Cotizaciones VALUES (80,6,36,5,50,DATE '2025-10-13');

INSERT INTO Cotizaciones VALUES (81,5,79,7,84,DATE '2025-10-19');
INSERT INTO Cotizaciones VALUES (82,3,41,11,13,DATE '2025-10-26');
INSERT INTO Cotizaciones VALUES (83,4,63,13,25,DATE '2025-11-03');
INSERT INTO Cotizaciones VALUES (84,8,57,17,22,DATE '2025-11-10');
INSERT INTO Cotizaciones VALUES (85,6,1,19,42,DATE '2025-11-16');
INSERT INTO Cotizaciones VALUES (86,5,28,4,18,DATE '2025-11-27');
INSERT INTO Cotizaciones VALUES (87,3,33,3,60,DATE '2025-12-04');
INSERT INTO Cotizaciones VALUES (88,4,70,11,95,DATE '2025-12-12');
INSERT INTO Cotizaciones VALUES (89,6,21,18,48,DATE '2025-12-19');
INSERT INTO Cotizaciones VALUES (90,5,46,8,8,DATE '2025-12-25');
INSERT INTO Cotizaciones VALUES (91,3,58,9,57,DATE '2025-12-28');
INSERT INTO Cotizaciones VALUES (92,4,90,12,9,DATE '2025-12-29');
INSERT INTO Cotizaciones VALUES (93,8,72,14,61,DATE '2025-12-30');
INSERT INTO Cotizaciones VALUES (94,5,17,1,78,DATE '2025-12-31');
INSERT INTO Cotizaciones VALUES (95,3,60,10,35,DATE '2025-01-17');
INSERT INTO Cotizaciones VALUES (96,4,8,13,21,DATE '2025-01-29');
INSERT INTO Cotizaciones VALUES (97,3,11,5,92,DATE '2025-02-10');
INSERT INTO Cotizaciones VALUES (98,5,19,14,77,DATE '2025-03-07');
INSERT INTO Cotizaciones VALUES (99,8,50,4,33,DATE '2025-04-19');
INSERT INTO Cotizaciones VALUES (100,6,5,10,64,DATE '2025-05-23');



--Tabla Categoria_Producto actualizada
INSERT INTO Categoria_Producto VALUES (2, 22, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 22, 1, 'Memorias', 'Memorias RAM DDR3 y DDR4');
INSERT INTO Categoria_Producto VALUES (1, 23, 3, 'Almacenamiento', 'Discos SSD y discos duros');
INSERT INTO Categoria_Producto VALUES (2, 23, 2, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 24, 5, 'Periféricos', 'Mouse, teclados y otros periféricos');
INSERT INTO Categoria_Producto VALUES (2, 24, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (2, 25, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 25, 4, 'Periféricos', 'Antenas WiFi, tarjetas de red');
INSERT INTO Categoria_Producto VALUES (4, 26, 2, 'Herramientas', 'Herramientas y sprays para limpieza');
INSERT INTO Categoria_Producto VALUES (2, 26, 1, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (4, 27, 3, 'Herramientas', 'Kit y cajas de herramientas');
INSERT INTO Categoria_Producto VALUES (2, 27, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (3, 28, 2, 'Energía', 'Fuentes de poder, baterías, cargadores');
INSERT INTO Categoria_Producto VALUES (2, 28, 5, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 29, 3, 'Almacenamiento', 'Discos SSD y discos duros');
INSERT INTO Categoria_Producto VALUES (2, 29, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (2, 30, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 30, 2, 'Periféricos', 'Ventiladores y refrigeración');

INSERT INTO Categoria_Producto VALUES (1, 31, 3, 'Memorias', 'Memorias RAM DDR3 y DDR4');
INSERT INTO Categoria_Producto VALUES (2, 31, 5, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (7, 32, 2, 'Consumibles', 'Pasta térmica y otros consumibles');
INSERT INTO Categoria_Producto VALUES (2, 32, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (3, 33, 4, 'Energía', 'Fuentes de poder, baterías, cargadores');
INSERT INTO Categoria_Producto VALUES (2, 33, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 34, 2, 'Periféricos', 'Tarjetas WiFi, Bluetooth y más');
INSERT INTO Categoria_Producto VALUES (2, 34, 1, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (6, 35, 4, 'Cables', 'Cables HDMI, USB, VGA, y más');
INSERT INTO Categoria_Producto VALUES (2, 35, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (4, 36, 5, 'Herramientas', 'Cases y cajas para PC');
INSERT INTO Categoria_Producto VALUES (2, 36, 2, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 37, 1, 'Periféricos', 'Cámaras web, micrófonos');
INSERT INTO Categoria_Producto VALUES (2, 37, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (4, 38, 3, 'Herramientas', 'Herramientas de diagnóstico y medición');
INSERT INTO Categoria_Producto VALUES (2, 38, 5, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (4, 39, 2, 'Herramientas', 'Limpieza y mantenimiento');
INSERT INTO Categoria_Producto VALUES (2, 39, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 40, 3, 'Software', 'Sistemas operativos y licencias');
INSERT INTO Categoria_Producto VALUES (2, 40, 4, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (5, 41, 2, 'Periféricos', 'Tarjetas de video, sonido y más');
INSERT INTO Categoria_Producto VALUES (2, 41, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 42, 1, 'Redes', 'Routers, switches y accesorios de red');
INSERT INTO Categoria_Producto VALUES (2, 42, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (4, 43, 5, 'Herramientas', 'Kit de destornilladores y precisión');
INSERT INTO Categoria_Producto VALUES (2, 43, 2, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 44, 3, 'Almacenamiento', 'Discos SSD y discos duros');
INSERT INTO Categoria_Producto VALUES (2, 44, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (2, 45, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (3, 45, 2, 'Energía', 'Fuentes de poder, baterías, cargadores');
INSERT INTO Categoria_Producto VALUES (5, 46, 3, 'Periféricos', 'Tarjetas de sonido y multimedia');
INSERT INTO Categoria_Producto VALUES (2, 46, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 47, 4, 'Periféricos', 'Hubs y accesorios USB');
INSERT INTO Categoria_Producto VALUES (2, 47, 5, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (3, 48, 2, 'Energía', 'Fuentes de poder, baterías, cargadores');
INSERT INTO Categoria_Producto VALUES (2, 48, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 49, 1, 'Memorias', 'Memorias RAM DDR3 y DDR4');
INSERT INTO Categoria_Producto VALUES (2, 49, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 50, 2, 'Periféricos', 'Adaptadores y cables USB');
INSERT INTO Categoria_Producto VALUES (2, 50, 5, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (3, 51, 3, 'Energía', 'Baterías y cargadores');
INSERT INTO Categoria_Producto VALUES (2, 51, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 52, 4, 'Redes', 'Switches y routers');
INSERT INTO Categoria_Producto VALUES (2, 52, 2, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (5, 53, 3, 'Periféricos', 'Teclados y mouse');
INSERT INTO Categoria_Producto VALUES (2, 53, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 54, 4, 'Periféricos', 'Mouse gamer y accesorios');
INSERT INTO Categoria_Producto VALUES (2, 54, 5, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 55, 2, 'Redes', 'Tarjetas WiFi y adaptadores');
INSERT INTO Categoria_Producto VALUES (2, 55, 3, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (4, 56, 1, 'Consumibles', 'Líquidos y herramientas de limpieza');
INSERT INTO Categoria_Producto VALUES (2, 56, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 57, 2, 'Almacenamiento', 'Discos SSD y discos duros');
INSERT INTO Categoria_Producto VALUES (2, 57, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (4, 58, 5, 'Consumibles', 'Material de organización y mantenimiento');
INSERT INTO Categoria_Producto VALUES (2, 58, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 59, 4, 'Periféricos', 'Parlantes y accesorios multimedia');
INSERT INTO Categoria_Producto VALUES (2, 59, 2, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (4, 60, 3, 'Herramientas', 'Kits de reparación y soldadura');
INSERT INTO Categoria_Producto VALUES (2, 60, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 61, 4, 'Cables', 'Cables DisplayPort y similares');
INSERT INTO Categoria_Producto VALUES (2, 61, 5, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 62, 2, 'Almacenamiento', 'Discos SSD y discos duros');
INSERT INTO Categoria_Producto VALUES (2, 62, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (4, 63, 1, 'Herramientas', 'Monitores y pantallas');
INSERT INTO Categoria_Producto VALUES (2, 63, 4, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (7, 64, 2, 'Consumibles', 'Pasta térmica y accesorios');
INSERT INTO Categoria_Producto VALUES (2, 64, 3, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 65, 5, 'Hardware', 'Placas madre y motherboards');
INSERT INTO Categoria_Producto VALUES (2, 65, 1, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 66, 4, 'Memorias', 'Memorias RAM DDR3 y DDR4');
INSERT INTO Categoria_Producto VALUES (2, 66, 2, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (1, 67, 3, 'Almacenamiento', 'Discos SSD y discos duros');
INSERT INTO Categoria_Producto VALUES (2, 67, 1, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Categoria_Producto VALUES (4, 68, 5, 'Consumibles', 'Cables y accesorios para PSU');
INSERT INTO Categoria_Producto VALUES (2, 68, 2, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (5, 69, 3, 'Periféricos', 'Tarjetas de video y GPU');
INSERT INTO Categoria_Producto VALUES (2, 69, 4, 'Hardware', 'Componentes y accesorios de computadora');
INSERT INTO Categoria_Producto VALUES (6, 70, 1, 'Periféricos', 'Ventiladores y refrigeración');
INSERT INTO Categoria_Producto VALUES (2, 70, 2, 'Hardware', 'Componentes y accesorios de computadora');

INSERT INTO Servicio_Cliente VALUES (1, 12, 1, 7, 3, TO_DATE('2025-04-15','YYYY-MM-DD'), 2, 70000);
INSERT INTO Servicio_Cliente VALUES (2, 45, 2, 10, 1, TO_DATE('2025-08-22','YYYY-MM-DD'), 1, 28000);
INSERT INTO Servicio_Cliente VALUES (3, 33, 3, 5, 4, TO_DATE('2025-01-10','YYYY-MM-DD'), 3, 126000);
INSERT INTO Servicio_Cliente VALUES (4, 89, 4, 22, 2, TO_DATE('2025-06-18','YYYY-MM-DD'), 1, 55000);
INSERT INTO Servicio_Cliente VALUES (5, 14, 5, 17, 5, TO_DATE('2025-12-05','YYYY-MM-DD'), 2, 30000);
INSERT INTO Servicio_Cliente VALUES (6, 76, 6, 31, 1, TO_DATE('2025-03-23','YYYY-MM-DD'), 3, 126000);
INSERT INTO Servicio_Cliente VALUES (7, 25, 7, 40, 3, TO_DATE('2025-09-15','YYYY-MM-DD'), 1, 2000);
INSERT INTO Servicio_Cliente VALUES (8, 88, 8, 29, 4, TO_DATE('2025-07-10','YYYY-MM-DD'), 2, 120000);
INSERT INTO Servicio_Cliente VALUES (9, 3, 9, 8, 2, TO_DATE('2025-02-22','YYYY-MM-DD'), 3, 63000);
INSERT INTO Servicio_Cliente VALUES (10, 52, 10, 4, 1, TO_DATE('2025-11-30','YYYY-MM-DD'), 1, 3500);
INSERT INTO Servicio_Cliente VALUES (11, 44, 11, 15, 5, TO_DATE('2025-05-17','YYYY-MM-DD'), 2, 24000);
INSERT INTO Servicio_Cliente VALUES (12, 2, 12, 11, 4, TO_DATE('2025-08-08','YYYY-MM-DD'), 1, 12000);
INSERT INTO Servicio_Cliente VALUES (13, 39, 13, 13, 2, TO_DATE('2025-04-25','YYYY-MM-DD'), 3, 39000);
INSERT INTO Servicio_Cliente VALUES (14, 80, 14, 14, 3, TO_DATE('2025-10-05','YYYY-MM-DD'), 1, 6000);
INSERT INTO Servicio_Cliente VALUES (15, 29, 15, 36, 1, TO_DATE('2025-01-14','YYYY-MM-DD'), 2, 110000);
INSERT INTO Servicio_Cliente VALUES (16, 77, 16, 37, 5, TO_DATE('2025-02-09','YYYY-MM-DD'), 3, 48000);
INSERT INTO Servicio_Cliente VALUES (17, 22, 17, 27, 4, TO_DATE('2025-03-20','YYYY-MM-DD'), 1, 2500);
INSERT INTO Servicio_Cliente VALUES (18, 18, 18, 19, 2, TO_DATE('2025-04-18','YYYY-MM-DD'), 2, 178000);
INSERT INTO Servicio_Cliente VALUES (19, 5, 19, 25, 3, TO_DATE('2025-05-22','YYYY-MM-DD'), 1, 9500);
INSERT INTO Servicio_Cliente VALUES (20, 61, 20, 30, 1, TO_DATE('2025-06-11','YYYY-MM-DD'), 1, 1800);

-- INSERTS 21 a 100:
INSERT INTO Servicio_Cliente VALUES (21, 14, 1, 8, 2, TO_DATE('2025-07-03','YYYY-MM-DD'), 1, 35000);
INSERT INTO Servicio_Cliente VALUES (22, 9, 2, 19, 4, TO_DATE('2025-08-15','YYYY-MM-DD'), 2, 56000);
INSERT INTO Servicio_Cliente VALUES (23, 30, 3, 33, 5, TO_DATE('2025-09-28','YYYY-MM-DD'), 3, 126000);
INSERT INTO Servicio_Cliente VALUES (24, 1, 4, 6, 1, TO_DATE('2025-10-12','YYYY-MM-DD'), 1, 55000);
INSERT INTO Servicio_Cliente VALUES (25, 41, 5, 17, 3, TO_DATE('2025-11-24','YYYY-MM-DD'), 1, 15000);
INSERT INTO Servicio_Cliente VALUES (26, 27, 6, 20, 2, TO_DATE('2025-01-08','YYYY-MM-DD'), 3, 126000);
INSERT INTO Servicio_Cliente VALUES (27, 55, 7, 21, 4, TO_DATE('2025-02-14','YYYY-MM-DD'), 2, 4000);
INSERT INTO Servicio_Cliente VALUES (28, 18, 8, 7, 1, TO_DATE('2025-03-27','YYYY-MM-DD'), 3, 180000);
INSERT INTO Servicio_Cliente VALUES (29, 63, 9, 26, 5, TO_DATE('2025-04-30','YYYY-MM-DD'), 1, 21000);
INSERT INTO Servicio_Cliente VALUES (30, 38, 10, 12, 3, TO_DATE('2025-05-14','YYYY-MM-DD'), 1, 3500);
INSERT INTO Servicio_Cliente VALUES (31, 34, 11, 35, 4, TO_DATE('2025-06-22','YYYY-MM-DD'), 3, 36000);
INSERT INTO Servicio_Cliente VALUES (32, 16, 12, 1, 2, TO_DATE('2025-07-18','YYYY-MM-DD'), 2, 24000);
INSERT INTO Servicio_Cliente VALUES (33, 21, 13, 9, 1, TO_DATE('2025-08-05','YYYY-MM-DD'), 1, 13000);
INSERT INTO Servicio_Cliente VALUES (34, 28, 14, 13, 5, TO_DATE('2025-09-21','YYYY-MM-DD'), 2, 12000);
INSERT INTO Servicio_Cliente VALUES (35, 13, 15, 22, 3, TO_DATE('2025-10-29','YYYY-MM-DD'), 3, 165000);
INSERT INTO Servicio_Cliente VALUES (36, 42, 16, 27, 4, TO_DATE('2025-11-04','YYYY-MM-DD'), 1, 16000);
INSERT INTO Servicio_Cliente VALUES (37, 39, 17, 8, 2, TO_DATE('2025-12-09','YYYY-MM-DD'), 1, 2500);
INSERT INTO Servicio_Cliente VALUES (38, 17, 18, 15, 1, TO_DATE('2025-01-16','YYYY-MM-DD'), 3, 267000);
INSERT INTO Servicio_Cliente VALUES (39, 26, 19, 19, 4, TO_DATE('2025-02-21','YYYY-MM-DD'), 1, 9500);
INSERT INTO Servicio_Cliente VALUES (40, 15, 20, 5, 3, TO_DATE('2025-03-23','YYYY-MM-DD'), 2, 3600);
INSERT INTO Servicio_Cliente VALUES (41, 44, 1, 28, 2, TO_DATE('2025-04-25','YYYY-MM-DD'), 3, 105000);
INSERT INTO Servicio_Cliente VALUES (42, 10, 2, 30, 5, TO_DATE('2025-05-29','YYYY-MM-DD'), 1, 28000);
INSERT INTO Servicio_Cliente VALUES (43, 22, 3, 21, 1, TO_DATE('2025-06-30','YYYY-MM-DD'), 2, 84000);
INSERT INTO Servicio_Cliente VALUES (44, 8, 4, 18, 3, TO_DATE('2025-07-02','YYYY-MM-DD'), 1, 55000);
INSERT INTO Servicio_Cliente VALUES (45, 5, 5, 11, 4, TO_DATE('2025-08-14','YYYY-MM-DD'), 3, 45000);
INSERT INTO Servicio_Cliente VALUES (46, 31, 6, 25, 5, TO_DATE('2025-09-18','YYYY-MM-DD'), 1, 42000);
INSERT INTO Servicio_Cliente VALUES (47, 19, 7, 6, 2, TO_DATE('2025-10-25','YYYY-MM-DD'), 1, 2000);
INSERT INTO Servicio_Cliente VALUES (48, 7, 8, 33, 1, TO_DATE('2025-11-07','YYYY-MM-DD'), 2, 120000);
INSERT INTO Servicio_Cliente VALUES (49, 60, 9, 13, 5, TO_DATE('2025-12-13','YYYY-MM-DD'), 3, 63000);
INSERT INTO Servicio_Cliente VALUES (50, 4, 10, 19, 3, TO_DATE('2025-01-20','YYYY-MM-DD'), 1, 3500);
INSERT INTO Servicio_Cliente VALUES (51, 23, 11, 22, 2, TO_DATE('2025-02-28','YYYY-MM-DD'), 2, 24000);
INSERT INTO Servicio_Cliente VALUES (52, 24, 12, 24, 4, TO_DATE('2025-03-08','YYYY-MM-DD'), 3, 36000);
INSERT INTO Servicio_Cliente VALUES (53, 46, 13, 14, 1, TO_DATE('2025-04-16','YYYY-MM-DD'), 1, 13000);
INSERT INTO Servicio_Cliente VALUES (54, 50, 14, 17, 2, TO_DATE('2025-05-27','YYYY-MM-DD'), 2, 12000);
INSERT INTO Servicio_Cliente VALUES (55, 32, 15, 28, 5, TO_DATE('2025-06-15','YYYY-MM-DD'), 3, 165000);
INSERT INTO Servicio_Cliente VALUES (56, 35, 16, 9, 3, TO_DATE('2025-07-21','YYYY-MM-DD'), 1, 16000);
INSERT INTO Servicio_Cliente VALUES (57, 38, 17, 31, 1, TO_DATE('2025-08-30','YYYY-MM-DD'), 1, 2500);
INSERT INTO Servicio_Cliente VALUES (58, 40, 18, 26, 2, TO_DATE('2025-09-06','YYYY-MM-DD'), 2, 178000);
INSERT INTO Servicio_Cliente VALUES (59, 43, 19, 12, 4, TO_DATE('2025-10-10','YYYY-MM-DD'), 3, 28500);
INSERT INTO Servicio_Cliente VALUES (60, 47, 20, 20, 5, TO_DATE('2025-11-29','YYYY-MM-DD'), 1, 1800);
INSERT INTO Servicio_Cliente VALUES (61, 51, 1, 29, 3, TO_DATE('2025-12-18','YYYY-MM-DD'), 2, 70000);
INSERT INTO Servicio_Cliente VALUES (62, 53, 2, 7, 1, TO_DATE('2025-01-26','YYYY-MM-DD'), 3, 84000);
INSERT INTO Servicio_Cliente VALUES (63, 54, 3, 21, 4, TO_DATE('2025-02-05','YYYY-MM-DD'), 1, 42000);
INSERT INTO Servicio_Cliente VALUES (64, 56, 4, 33, 2, TO_DATE('2025-03-13','YYYY-MM-DD'), 2, 110000);
INSERT INTO Servicio_Cliente VALUES (65, 57, 5, 24, 3, TO_DATE('2025-04-27','YYYY-MM-DD'), 3, 45000);
INSERT INTO Servicio_Cliente VALUES (66, 58, 6, 16, 5, TO_DATE('2025-05-31','YYYY-MM-DD'), 1, 42000);
INSERT INTO Servicio_Cliente VALUES (67, 59, 7, 30, 1, TO_DATE('2025-06-19','YYYY-MM-DD'), 2, 4000);
INSERT INTO Servicio_Cliente VALUES (68, 62, 8, 18, 3, TO_DATE('2025-07-23','YYYY-MM-DD'), 3, 180000);
INSERT INTO Servicio_Cliente VALUES (69, 64, 9, 7, 4, TO_DATE('2025-08-28','YYYY-MM-DD'), 1, 21000);
INSERT INTO Servicio_Cliente VALUES (70, 65, 10, 29, 2, TO_DATE('2025-09-26','YYYY-MM-DD'), 2, 7000);
INSERT INTO Servicio_Cliente VALUES (71, 66, 11, 11, 1, TO_DATE('2025-10-31','YYYY-MM-DD'), 1, 12000);
INSERT INTO Servicio_Cliente VALUES (72, 67, 12, 13, 5, TO_DATE('2025-11-11','YYYY-MM-DD'), 3, 54000);
INSERT INTO Servicio_Cliente VALUES (73, 68, 13, 22, 3, TO_DATE('2025-12-20','YYYY-MM-DD'), 2, 26000);
INSERT INTO Servicio_Cliente VALUES (74, 69, 14, 26, 2, TO_DATE('2025-01-22','YYYY-MM-DD'), 1, 6000);
INSERT INTO Servicio_Cliente VALUES (75, 70, 15, 27, 4, TO_DATE('2025-02-14','YYYY-MM-DD'), 3, 165000);
INSERT INTO Servicio_Cliente VALUES (76, 71, 16, 35, 1, TO_DATE('2025-03-05','YYYY-MM-DD'), 2, 32000);
INSERT INTO Servicio_Cliente VALUES (77, 72, 17, 1, 5, TO_DATE('2025-04-08','YYYY-MM-DD'), 1, 2500);
INSERT INTO Servicio_Cliente VALUES (78, 73, 18, 4, 2, TO_DATE('2025-05-16','YYYY-MM-DD'), 3, 267000);
INSERT INTO Servicio_Cliente VALUES (79, 74, 19, 9, 4, TO_DATE('2025-06-28','YYYY-MM-DD'), 2, 19000);
INSERT INTO Servicio_Cliente VALUES (80, 75, 20, 15, 3, TO_DATE('2025-07-31','YYYY-MM-DD'), 1, 1800);
INSERT INTO Servicio_Cliente VALUES (81, 2, 1, 14, 1, TO_DATE('2025-08-15','YYYY-MM-DD'), 2, 70000);
INSERT INTO Servicio_Cliente VALUES (82, 3, 2, 20, 2, TO_DATE('2025-09-17','YYYY-MM-DD'), 3, 84000);
INSERT INTO Servicio_Cliente VALUES (83, 4, 3, 16, 3, TO_DATE('2025-10-19','YYYY-MM-DD'), 1, 42000);
INSERT INTO Servicio_Cliente VALUES (84, 5, 4, 13, 4, TO_DATE('2025-11-21','YYYY-MM-DD'), 2, 110000);
INSERT INTO Servicio_Cliente VALUES (85, 6, 5, 22, 5, TO_DATE('2025-12-23','YYYY-MM-DD'), 3, 45000);
INSERT INTO Servicio_Cliente VALUES (86, 7, 6, 30, 1, TO_DATE('2025-01-25','YYYY-MM-DD'), 1, 42000);
INSERT INTO Servicio_Cliente VALUES (87, 8, 7, 19, 2, TO_DATE('2025-02-27','YYYY-MM-DD'), 2, 4000);
INSERT INTO Servicio_Cliente VALUES (88, 9, 8, 8, 3, TO_DATE('2025-03-29','YYYY-MM-DD'), 3, 180000);
INSERT INTO Servicio_Cliente VALUES (89, 10, 9, 5, 4, TO_DATE('2025-04-30','YYYY-MM-DD'), 1, 21000);
INSERT INTO Servicio_Cliente VALUES (90, 11, 10, 7, 5, TO_DATE('2025-05-31','YYYY-MM-DD'), 2, 7000);
INSERT INTO Servicio_Cliente VALUES (91, 12, 11, 12, 1, TO_DATE('2025-06-30','YYYY-MM-DD'), 3, 36000);
INSERT INTO Servicio_Cliente VALUES (92, 13, 12, 18, 2, TO_DATE('2025-07-31','YYYY-MM-DD'), 1, 12000);
INSERT INTO Servicio_Cliente VALUES (93, 14, 13, 20, 3, TO_DATE('2025-08-31','YYYY-MM-DD'), 2, 26000);
INSERT INTO Servicio_Cliente VALUES (94, 15, 14, 25, 4, TO_DATE('2025-09-30','YYYY-MM-DD'), 3, 18000);
INSERT INTO Servicio_Cliente VALUES (95, 16, 15, 28, 5, TO_DATE('2025-10-30','YYYY-MM-DD'), 1, 55000);
INSERT INTO Servicio_Cliente VALUES (96, 17, 16, 4, 1, TO_DATE('2025-11-30','YYYY-MM-DD'), 2, 32000);
INSERT INTO Servicio_Cliente VALUES (97, 18, 17, 1, 2, TO_DATE('2025-12-30','YYYY-MM-DD'), 3, 7500);
INSERT INTO Servicio_Cliente VALUES (98, 19, 18, 9, 3, TO_DATE('2025-01-31','YYYY-MM-DD'), 1, 89000);
INSERT INTO Servicio_Cliente VALUES (99, 20, 19, 15, 4, TO_DATE('2025-02-28','YYYY-MM-DD'), 2, 19000);
INSERT INTO Servicio_Cliente VALUES (100, 21, 20, 11, 5, TO_DATE('2025-03-31','YYYY-MM-DD'), 3, 5400);
