ALTER TABLE Estado
MODIFY (Nombre_Estado VARCHAR2(20));

-- Tabla Estado
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (1, 'Activo', 'Disponible');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (2, 'Inactivo', 'No disponible');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (3, 'Pendiente', 'En espera');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (4, 'Proceso', 'En proceso');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (5, 'Cancelado', 'Anulado');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (6, 'Completado', 'Finalizado');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (7, 'Vencido', 'Fuera de tiempo');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (8, 'Programado', 'Con fecha');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (9, 'Retrasado', 'Fuera de plazo');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (10, 'Aceptado', 'Aprobado');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (11, 'Rechazado', 'Denegado');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (12, 'Facturado', 'Con factura');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (13, 'Pagado', 'Con pago');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (14, 'Parcial', 'Pago parcial');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (15, 'Verificado', 'Chequeado');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (16, 'Revisión', 'En revisión');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (17, 'Disponible', 'Listo uso');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (18, 'Agotado', 'Sin stock');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (19, 'Reservado', 'Apartado');
INSERT INTO Estado (Estado_ID, Nombre_Estado, Descripcion_Estado) VALUES (20, 'Desactivado', 'Fuera de uso');


-- Tabla clientes 
INSERT INTO Clientes VALUES (1, 1, 'María', 'González', 'San José', 'maria.gonzalez@gmail.com');
INSERT INTO Clientes VALUES (2, 1, 'Juan', 'Rodríguez', 'Cartago', 'juan.rodriguez@hotmail.com');
INSERT INTO Clientes VALUES (3, 2, 'Carlos', 'Soto', 'Alajuela', 'carlos.soto@yahoo.com');
INSERT INTO Clientes VALUES (4, 1, 'Ana', 'Jiménez', 'Heredia', 'ana.jimenez@gmail.com');
INSERT INTO Clientes VALUES (5, 3, 'Luis', 'Pérez', 'Puntarenas', 'luis.perez@outlook.com');
INSERT INTO Clientes VALUES (6, 1, 'Laura', 'Ramírez', 'Cartago', 'laura.ramirez@gmail.com');
INSERT INTO Clientes VALUES (7, 4, 'Pedro', 'Campos', 'Guanacaste', 'pedro.campos@gmail.com');
INSERT INTO Clientes VALUES (8, 1, 'Sofía', 'Vargas', 'San José', 'sofia.vargas@gmail.com');
INSERT INTO Clientes VALUES (9, 2, 'Andrés', 'Araya', 'Heredia', 'andres.araya@hotmail.com');
INSERT INTO Clientes VALUES (10, 1, 'Gabriela', 'Rojas', 'Cartago', 'gabriela.rojas@gmail.com');
INSERT INTO Clientes VALUES (11, 5, 'Ricardo', 'Solano', 'San José', 'ricardo.solano@outlook.com');
INSERT INTO Clientes VALUES (12, 1, 'Daniela', 'Acosta', 'Alajuela', 'daniela.acosta@gmail.com');
INSERT INTO Clientes VALUES (13, 3, 'Jorge', 'Cordero', 'Puntarenas', 'jorge.cordero@gmail.com');
INSERT INTO Clientes VALUES (14, 1, 'Natalia', 'Zuñiga', 'Heredia', 'natalia.zuniga@yahoo.com');
INSERT INTO Clientes VALUES (15, 1, 'Esteban', 'Mora', 'San José', 'esteban.mora@gmail.com');
INSERT INTO Clientes VALUES (16, 4, 'Patricia', 'Marín', 'Cartago', 'patricia.marin@gmail.com');
INSERT INTO Clientes VALUES (17, 1, 'Diego', 'Salazar', 'Alajuela', 'diego.salazar@hotmail.com');
INSERT INTO Clientes VALUES (18, 2, 'Josué', 'Leiva', 'Guanacaste', 'josue.leiva@gmail.com');
INSERT INTO Clientes VALUES (19, 1, 'Rebeca', 'Ruiz', 'San José', 'rebeca.ruiz@gmail.com');
INSERT INTO Clientes VALUES (20, 1, 'Kevin', 'Vega', 'Heredia', 'kevin.vega@outlook.com');
INSERT INTO Clientes VALUES (21, 3, 'Isabel', 'Navarro', 'Cartago', 'isabel.navarro@gmail.com');
INSERT INTO Clientes VALUES (22, 1, 'Fernanda', 'Calderón', 'Alajuela', 'fernanda.calderon@yahoo.com');
INSERT INTO Clientes VALUES (23, 5, 'Felipe', 'Ureña', 'San José', 'felipe.urena@gmail.com');
INSERT INTO Clientes VALUES (24, 1, 'Karina', 'Montero', 'Guanacaste', 'karina.montero@gmail.com');
INSERT INTO Clientes VALUES (25, 2, 'Mauricio', 'Vargas', 'Cartago', 'mauricio.vargas@hotmail.com');
INSERT INTO Clientes VALUES (26, 1, 'Valeria', 'Segura', 'Heredia', 'valeria.segura@gmail.com');
INSERT INTO Clientes VALUES (27, 4, 'Paola', 'Hernández', 'San José', 'paola.hernandez@outlook.com');
INSERT INTO Clientes VALUES (28, 1, 'Óscar', 'Carrillo', 'Cartago', 'oscar.carrillo@gmail.com');
INSERT INTO Clientes VALUES (29, 3, 'Jennifer', 'Sandí', 'Alajuela', 'jennifer.sandi@gmail.com');
INSERT INTO Clientes VALUES (30, 1, 'Alex', 'Barquero', 'San José', 'alex.barquero@hotmail.com');
INSERT INTO Clientes VALUES (31, 2, 'Camila', 'Chaves', 'Heredia', 'camila.chaves@gmail.com');
INSERT INTO Clientes VALUES (32, 1, 'Fabián', 'Rojas', 'Alajuela', 'fabian.rojas@gmail.com');
INSERT INTO Clientes VALUES (33, 1, 'Tatiana', 'López', 'Puntarenas', 'tatiana.lopez@hotmail.com');
INSERT INTO Clientes VALUES (34, 3, 'Sebastián', 'Calvo', 'San José', 'sebastian.calvo@gmail.com');
INSERT INTO Clientes VALUES (35, 1, 'Mónica', 'Espinoza', 'Cartago', 'monica.espinoza@gmail.com');
INSERT INTO Clientes VALUES (36, 5, 'Alexander', 'Granados', 'Heredia', 'alexander.granados@gmail.com');
INSERT INTO Clientes VALUES (37, 4, 'Marcela', 'Vargas', 'San José', 'marcela.vargas@hotmail.com');
INSERT INTO Clientes VALUES (38, 1, 'Adriana', 'Alfaro', 'San José', 'adriana.alfaro@gmail.com');
INSERT INTO Clientes VALUES (39, 2, 'Pablo', 'Cubero', 'Alajuela', 'pablo.cubero@hotmail.com');
INSERT INTO Clientes VALUES (40, 1, 'Andrea', 'Céspedes', 'Cartago', 'andrea.cespedes@gmail.com');


--Tabla de inventario


INSERT INTO Inventario VALUES (1, 1, 'SSD Kingston 240GB', 'Unidad estado sólido nueva', 35000, 12);
INSERT INTO Inventario VALUES (2, 1, 'Memoria RAM 8GB DDR4', 'Kingston HyperX nueva', 28000, 15);
INSERT INTO Inventario VALUES (3, 1, 'Fuente poder 600W', 'EVGA 600W usada funcional', 42000, 4);
INSERT INTO Inventario VALUES (4, 1, 'Placa Madre ASUS H110M', 'ASUS Intel usada', 55000, 3);
INSERT INTO Inventario VALUES (5, 2, 'Cargadores universales laptop', 'Genéricos nuevos', 15000, 10);
INSERT INTO Inventario VALUES (6, 1, 'Disco duro 1TB', 'Seagate SATA nuevo', 42000, 8);
INSERT INTO Inventario VALUES (7, 3, 'Kit tornillos PC', 'Bolsitas de 50pzas nuevos', 2000, 25);
INSERT INTO Inventario VALUES (8, 1, 'Tarjeta video GT 1030', 'NVIDIA usada', 60000, 2);
INSERT INTO Inventario VALUES (9, 1, 'Cable HDMI 1.5m', 'Genérico nuevo', 3500, 20);
INSERT INTO Inventario VALUES (10, 4, 'Spray aire comprimido', 'Limpieza interna nuevo', 3000, 18);
INSERT INTO Inventario VALUES (11, 1, 'Pasta térmica Arctic', '1g nueva original', 4500, 30);
INSERT INTO Inventario VALUES (12, 1, 'Memoria RAM 4GB DDR3', 'Kingston usada', 12000, 7);
INSERT INTO Inventario VALUES (13, 2, 'Mouse Logitech M90', 'Nuevo retail', 7000, 11);
INSERT INTO Inventario VALUES (14, 1, 'Teclado genérico USB', 'Nuevo económico', 6000, 9);
INSERT INTO Inventario VALUES (15, 1, 'Pantalla LCD 15.6"', 'Repuesto laptop usado', 55000, 3);
INSERT INTO Inventario VALUES (16, 1, 'Batería HP 14"', 'Repuesto usada', 30000, 5);
INSERT INTO Inventario VALUES (17, 3, 'Alcohol isopropílico', 'Botella 99% nuevo', 2500, 14);
INSERT INTO Inventario VALUES (18, 1, 'SSD NVMe 500GB', 'WesternDigital Blue nuevo', 89000, 6);
INSERT INTO Inventario VALUES (19, 1, 'Tarjeta WiFi USB', 'TP-Link nuevo', 9500, 12);
INSERT INTO Inventario VALUES (20, 5, 'Cables SATA III', 'Nuevos empacados', 1800, 22);
INSERT INTO Inventario VALUES (21, 1, 'Disipador Cooler Master', 'Con ventilador usado', 27000, 5);
INSERT INTO Inventario VALUES (22, 2, 'Memoria RAM 16GB DDR4', 'Crucial Ballistix nueva', 58000, 4);
INSERT INTO Inventario VALUES (23, 1, 'SSD 120GB Genérico', 'Nuevo en caja', 25000, 9);
INSERT INTO Inventario VALUES (24, 1, 'Hub USB 4 puertos', 'TP-Link nuevo', 8000, 15);
INSERT INTO Inventario VALUES (25, 1, 'Antena WiFi interna', 'Repuesto laptop usado', 3500, 6);
INSERT INTO Inventario VALUES (26, 3, 'Pantalla LED 17"', 'Para PC, usada', 45000, 3);
INSERT INTO Inventario VALUES (27, 4, 'Caja herramienta básica', 'Reparación portátil', 20000, 7);
INSERT INTO Inventario VALUES (28, 1, 'Cargador Lenovo 20V', 'Nuevo original', 23000, 5);
INSERT INTO Inventario VALUES (29, 1, 'Tarjeta madre MSI B450', 'AMD Ryzen soporte nueva', 98000, 2);
INSERT INTO Inventario VALUES (30, 1, 'Ventilador gabinete 120mm', 'Cooler Master nuevo', 5500, 20);
INSERT INTO Inventario VALUES (31, 2, 'Memoria RAM 2GB DDR2', 'Usada funcionando', 5000, 8);
INSERT INTO Inventario VALUES (32, 1, 'Pasta térmica genérica', 'Nuevas en sobre', 1800, 25);
INSERT INTO Inventario VALUES (33, 1, 'Fuente genérica 450W', 'Usada prueba', 21000, 4);
INSERT INTO Inventario VALUES (34, 1, 'Módulo WiFi M.2', 'Laptop nuevo', 12000, 3);
INSERT INTO Inventario VALUES (35, 1, 'Cable VGA 1.5m', 'Genérico nuevo', 2800, 12);
INSERT INTO Inventario VALUES (36, 3, 'Caja ATX semitorre', 'Case usado en buen estado', 39000, 2);
INSERT INTO Inventario VALUES (37, 1, 'Cámara web USB', 'Logitech nueva', 27000, 6);
INSERT INTO Inventario VALUES (38, 1, 'Multímetro digital', 'Genérico nuevo', 16000, 4);
INSERT INTO Inventario VALUES (39, 1, 'Soplador eléctrico', 'Limpieza de hardware', 46000, 2);
INSERT INTO Inventario VALUES (40, 5, 'CD Windows 10 Pro OEM', 'Licencia incluida nueva', 60000, 3);
INSERT INTO Inventario VALUES (41, 1, 'Tarjeta de video GTX 1050 Ti', 'NVIDIA usada funcionando', 135000, 2);
INSERT INTO Inventario VALUES (42, 1, 'Router TP-Link Archer C20', 'Nuevo empacado', 29000, 6);
INSERT INTO Inventario VALUES (43, 3, 'Kit destornilladores de precisión', 'Para reparación, nuevo', 8500, 10);
INSERT INTO Inventario VALUES (44, 1, 'Disco duro 500GB', 'Western Digital usado', 18000, 7);
INSERT INTO Inventario VALUES (45, 2, 'Placa madre Dell OEM', 'Repuesto usado', 25000, 3);
INSERT INTO Inventario VALUES (46, 1, 'Tarjeta sonido PCIe', 'Creative nueva', 17000, 5);
INSERT INTO Inventario VALUES (47, 1, 'Hub USB tipo C', 'Nuevo de 6 puertos', 12000, 8);
INSERT INTO Inventario VALUES (48, 5, 'Fuente certificada Corsair 650W', 'Nueva 80+ Bronze', 89000, 1);
INSERT INTO Inventario VALUES (49, 1, 'Memoria RAM 32GB DDR4', 'Corsair Vengeance nueva', 145000, 2);
INSERT INTO Inventario VALUES (50, 1, 'Adaptador USB – Ethernet', 'Nuevo genérico', 6000, 15);
INSERT INTO Inventario VALUES (51, 3, 'Batería Dell Inspiron', 'Usada funcional', 28000, 4);
INSERT INTO Inventario VALUES (52, 1, 'Switch 8 puertos', 'TP-Link nuevo', 22000, 6);
INSERT INTO Inventario VALUES (53, 1, 'Teclado mecánico Redragon', 'Nuevo iluminación RGB', 35000, 5);
INSERT INTO Inventario VALUES (54, 2, 'Mouse gamer Razer', 'Usado buen estado', 25000, 3);
INSERT INTO Inventario VALUES (55, 1, 'Placa WiFi PCIe', 'ASUS nueva', 19000, 7);
INSERT INTO Inventario VALUES (56, 1, 'Kit limpieza premium', 'Brochas y líquidos nuevo', 7000, 13);
INSERT INTO Inventario VALUES (57, 1, 'M.2 NVMe 250GB', 'Samsung 970 usado', 42000, 4);
INSERT INTO Inventario VALUES (58, 4, 'Cinta envolvente cables', 'Organizadora nueva', 2000, 30);
INSERT INTO Inventario VALUES (59, 1, 'Parlantes Logitech Z120', 'Nuevo 2.0 USB', 16000, 9);
INSERT INTO Inventario VALUES (60, 5, 'Kit reparación soldadura', 'Herramientas intermedias', 31000, 3);
INSERT INTO Inventario VALUES (61, 1, 'Cable DisplayPort 2m', 'Genérico nuevo', 5500, 12);
INSERT INTO Inventario VALUES (62, 1, 'SSD 1TB Crucial', 'Nuevo en caja', 185000, 3);
INSERT INTO Inventario VALUES (63, 3, 'Monitor 24" LG', 'Usado sin caja', 85000, 2);
INSERT INTO Inventario VALUES (64, 1, 'Soporte pasta térmica', 'Jeringa Arctic nueva', 6000, 20);
INSERT INTO Inventario VALUES (65, 1, 'Motherboard ASUS Prime B460', 'Nueva Intel 10th gen', 110000, 2);
INSERT INTO Inventario VALUES (66, 2, 'Memoria RAM 8GB DDR3', 'Usada Crucial', 15000, 6);
INSERT INTO Inventario VALUES (67, 1, 'SSD Kingston 480GB', 'Nuevo', 65000, 4);
INSERT INTO Inventario VALUES (68, 4, 'Cableado modular PSU', 'Repuestos Corsair', 9000, 10);
INSERT INTO Inventario VALUES (69, 1, 'Tarjeta gráfica RX 570', 'Usada Gigabyte', 125000, 2);
INSERT INTO Inventario VALUES (70, 1, 'Ventilador portátil USB', 'Mini nuevo', 2500, 25);
INSERT INTO Inventario VALUES (71, 3, 'Tarjeta WiFi Mini PCIe', 'Repuesto laptop usado', 9500, 6);
INSERT INTO Inventario VALUES (72, 1, 'Guantes antiestáticos', 'Nuevo par', 3000, 14);
INSERT INTO Inventario VALUES (73, 1, 'Cable USB tipo C 1m', 'Reforzado nuevo', 4000, 25);
INSERT INTO Inventario VALUES (74, 1, 'Spray limpiador contactos', 'Nuevo aerosol', 3800, 15);
INSERT INTO Inventario VALUES (75, 2, 'Placa madre HP OEM', 'Usada funcional', 20000, 3);
INSERT INTO Inventario VALUES (76, 1, 'Webcam 1080p genérica', 'Nueva', 17500, 6);
INSERT INTO Inventario VALUES (77, 1, 'Kit bandas sujetacables', '50 unidades', 1500, 30);
INSERT INTO Inventario VALUES (78, 5, 'SSD NVMe 2TB Samsung', 'Nuevo 980 PRO', 250000, 1);
INSERT INTO Inventario VALUES (79, 1, 'Unidad DVD externa USB', 'ASUS nueva', 27000, 4);
INSERT INTO Inventario VALUES (80, 1, 'Tarjeta FireWire PCIe', 'Repuesto usada', 12000, 2);
INSERT INTO Inventario VALUES (81, 1, 'Extensor WiFi TP-Link', 'Nuevo empacado', 23000, 5);
INSERT INTO Inventario VALUES (82, 2, 'Memoria RAM 1GB DDR2', 'Usada Kingston', 3500, 7);
INSERT INTO Inventario VALUES (83, 1, 'Tarjeta captura video USB', 'Genérico nuevo', 18000, 6);
INSERT INTO Inventario VALUES (84, 1, 'Controlador Fan RGB', 'Cooler Master nuevo', 9000, 8);
INSERT INTO Inventario VALUES (85, 3, 'Pantalla LCD 14"', 'Repuesto laptop usada', 42000, 3);
INSERT INTO Inventario VALUES (86, 1, 'Fuente Thermaltake 750W', 'Nueva 80+ Gold', 120000, 2);
INSERT INTO Inventario VALUES (87, 1, 'Soporte monitor articulado', 'Genérico nuevo', 33000, 4);
INSERT INTO Inventario VALUES (88, 5, 'Mouse pad grande RGB', 'Gamer nuevo', 10500, 10);
INSERT INTO Inventario VALUES (89, 1, 'Tarjeta red gigabit PCIe', 'TP-Link nueva', 15000, 7);
INSERT INTO Inventario VALUES (90, 1, 'Memoria Optane Intel 32GB', 'Nueva acelerador', 65000, 3);
INSERT INTO Inventario VALUES (91, 4, 'Pantalla Touch 13.3"', 'Usada ultrabook', 62000, 2);
INSERT INTO Inventario VALUES (92, 1, 'Kit extractor teclas', 'Mecánicos nuevo', 2500, 20);
INSERT INTO Inventario VALUES (93, 1, 'Switch KVM 2 Puertos', 'Controlar 2 PCs nuevo', 27500, 3);
INSERT INTO Inventario VALUES (94, 2, 'Tarjeta GT 710', 'NVIDIA usada', 23000, 4);
INSERT INTO Inventario VALUES (95, 1, 'Hub USB 7 puertos', 'Genérico nuevo', 9500, 9);
INSERT INTO Inventario VALUES (96, 1, 'SSD Patriot 256GB', 'Nuevo en caja', 38000, 5);
INSERT INTO Inventario VALUES (97, 2, 'Regrabador DVD SATA', 'Usado funcional', 9500, 6);
INSERT INTO Inventario VALUES (98, 1, 'Adaptador PS/2 a USB', 'Nuevo', 1800, 15);
INSERT INTO Inventario VALUES (99, 3, 'Microprocesador i5-3470', 'Usado Intel', 48000, 3);
INSERT INTO Inventario VALUES (100, 1, 'Tarjeta RAID PCIe', 'Nuevas 4 puertos SATA', 68000, 2);

